### ISSUE TITLE
Module Rewritten

### ISSUE THREAD

**Issue by dieskim** [shivakumars/Titanium-Android-Count.ly#5]
Hey guys,

I had to rewrite the module to be able to build in some new features. I also went ahead and changed the module name and many functions so that the new module now functions exactly as the the iOS module does - thus you only need one set of functions for both platforms.

I am not sure how we could merge this completely different Repo with this original one?

https://github.com/dieskim/Count.ly-Titanium-Android

**Comment by shivakumars** [comment]
Hey,

It is good that you had rewritten the module exactly like iOS module structure. Instead of merging the repos, i will better create a link to your repo and show it in this repo's read me.
